apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      affinity:
       nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - myserver02
      containers:
      - name: springboot
        image: gymlet/test_app:1.0
        ports:
        - containerPort: 8080
        resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "516Mi"
              cpu: "500m"
      

